### ISSUE TITLE
Cannot add torrent from .torrent file

### ISSUE THREAD

**Issue by nitnelave** [erickok/transdroid#192] opened 2015-02-20 18:37 UTC
Hello,

I'm using Transdrone 2.3.0 on android. I setup the connection details with my rtorrent server, and I can add torrents from the browser. 

However, I cannot add local .torrent files. When I click on "adding torrent from file", then navigate to the "Downloads" folder, the local .torrent files are greyed out, I can't select them.
If I use an external file chooser app, (FX File Chooser  in my case) to force-select them, I get "Unfortunately, Transdrone has crashed".

Any ideas?

Thanks

**Comment by ByteFlinger** [comment] 2015-04-25 17:11
Having the issue here. All files appear greyed out on the normal android file picker and if I choose another one like EX File Explorer using the "Android way" the app crashes but it works if I use "the other way"

**Comment by erickok** [comment] 2015-06-01 13:49
Fixed in a3a595d for the next release (2.5.0-beta).

**Closed by erickok** 2015-06-01 13:49 UTC
Labels: bug

**Comment by R0nd** [comment] 2016-05-04 03:59
Reproduces in 2.5.6 on android 6.0.1

**Comment by geyslan** [comment] 2016-05-11 09:05
Here same problem with 2.5.6 on 6.0.1.

**Comment by gaz2030** [comment] 2016-05-17 13:01
Also have this problem on 6.0.1 and 2.5.6

**Comment by gaz2030** [comment] 2016-05-18 08:14
I found if you go into settings/apps/ transdroid and give it permissions to storage it works as usual.

**Comment by geyslan** [comment] 2016-05-18 10:45
@gaz2030, that's right. It worked. But from the transdone the files are showed as gray (inaccessible).

**Comment by OblongCheese** [comment] 2016-08-31 07:21
This is still an issue. Android 6.0.1 (stock, Nexus 5) with latest Transdrone.

**Comment by erickok** [comment] 2016-09-02 09:45
If a file can be selected or not is also dependent on what the file is, namely if it has the proper mime type. You can always use a picker app such as Dir or 'open' files directly from the Downloads app, that should work.

**Comment by gryphonmyers** [comment] 2016-09-05 14:54
Problem for me as well. Even giving storage access, some files I get "cannot read .torrent file" no matter what and they wont add opening directly from browser either. These torrents work fine in other clients.

**Comment by erickok** [comment] 2016-09-05 15:29
Can you supply some examples? What sources? Do they carry a proper mime type? Typically files are greyed out (by Android) if they are not supported by the app (Transdroid).

**Comment by erickok** [comment] 2016-09-06 14:48
@gryphonmyers I tested the specific case you send me (via email) and it works fine. Just make sure you download the .torrent file first, since it is a private tracker and so sending the link directly to your server (the default action) does not work as your server would not have access to it.

**Comment by gryphonmyers** [comment] 2016-09-06 15:26
A power cycle fixed the "can't open torrent file" error I was getting. In
addition to adding storage app permissions, apparently you may also need to
restart

**Comment by NachbarsLumpi** [comment] 2017-01-02 21:02
Having this very same issue today on Android 6.0.1 altogether with Transdroid 2.5.7. When tapping the icon to add torrent file, the file picker opens up but all files are greyed out. Tapping the file explorer however lets me add files. When trying to add a file from the downloads transdroid bails "Can't read file". Any ideas?

**Comment by erickok** [comment] 2017-03-17 16:24
Note to self: https://developer.android.com/reference/android/support/v4/content/FileProvider.html
