### ISSUE TITLE
Labels for qBittorrent v.3.2

### ISSUE THREAD

**Issue by tebor8** [erickok/transdroid#215] opened 2015-06-16 02:17 UTC
I can't seem to set a label for the torrent I download in Transdroid for qBittorrent v.3.2. I have tried the recent Beta as well as Transdroid 2.3. This feature worked when I was back with uTorrent. Is it possible to implement this again? Thank you.

**Comment by erickok** [comment] 2015-11-24 10:48
Have to investigate if qBittorrent's web interface supports this.

**Comment by Seedthis** [comment] 2015-12-06 12:15
Hello Erick, just a confirmation that since the recent release of qBitorrent 3.3.0, we now have access to labels in the WebUI

Link : https://github.com/qbittorrent/qBittorrent/pull/3444

**Comment by m-9** [comment] 2016-02-21 14:10
recently moved from utorrent to qbittorrent; this is the only feature that I miss.
thanks eric! ive tried a lot of torrent managers for android and this is easily the best one.

**Comment by m-9** [comment] 2016-02-27 23:14
Moved to deluge, supports even more features than u torrent did. Labels, move files, set speeds etc. Great app, thanks Eric

**Comment by X-static** [comment] 2017-05-13 14:12
Hi. Any news about implementing labels for qbittorrent on Transdroid? I'm moving from deluge because of constant connection lost with transdoid and sonarr, and being able to use labels from transdroid would be great.

Thank you.

**Comment by erickok** [comment] 2017-11-17 20:56
Duplicate of #333 . Fixed.

**Closed by erickok** 2017-11-17 20:56 UTC
Labels: enhancement
