### ISSUE TITLE
Charge port uTorrrent

### ISSUE THREAD

**Issue by aislandener** [erickok/transdroid#334] opened 2016-10-14 17:11 UTC
Hello,
I would ask if you could put the option to change the server port at the time of the same configuration.
For already have a service running on the main door, which in this case is 8080 and set up uTorrent to run on port 48080, you could make the change in the source, would be grateful.

**Comment by erickok** [comment] 2016-10-14 18:28
Duplicate of #331, #323, #320, #314, #307, #270, #260... I must be doing something wrong. How can I make it more visible? It is the very first option in advanced settings... (Not trying to annoy, I am honestly asking.)

**Closed by erickok** 2016-10-14 18:28 UTC

**Comment by aislandener** [comment] 2016-10-14 18:32
Sorry,I am not view this option

Em sex, 14 de out de 2016 15:28, Eric Kok <notifications@github.com>
escreveu:
