### ISSUE TITLE
"Internal error building request" error appearing since latest release of Transdroid

### ISSUE THREAD

**Issue by SegiH** [erickok/transdroid#602] opened 2021-12-16 07:51 UTC
Since the latest update of Transdroid 8 days ago, I have been getting the error message "Internal error building request" many times throughout the day and Transdroid does not show any activity. When this happens, I press recents and swipe Transdroid away to close it and then launch it again and it loads normally. This only started after the latest update to Transdroid.

I went to the strings.xml and found the error message that has been popping up which is

`<string name="error_jsonrequesterror">Internal error building request</string>`

I think that I have traced this error to 
[transdroid/app/src/main/java/org/transdroid/core/gui/lists/LocalTorrent.java](https://github.com/erickok/transdroid/blob/d20d20012bc9d319e22614b6144f1933ec2ce984/app/src/main/java/org/transdroid/core/gui/lists/LocalTorrent.java#L68)

where its suddenly throwing a ParsingFailed DaemonException error
`
            case ParsingFailed:
                return R.string.error_jsonrequesterror;
`

which is strange since you added a MalformedUri case below this case. I don't know why this is happening but I have sent you the help logs and would be interested to know why this has been happened to me.

**Comment by erickok** [comment] 2021-12-17 16:05
We changed a bit how the connections are managed inside Transdroid. Can you tell me what torrent client you are connecting too and which version? Could you also check in the menu -> Help -> Send error report and send me (or better yet copy here) the connection log?

**Comment by SegiH** [comment] 2021-12-18 00:28
My connection is to a Deluge 1.2+ server. I sent the logs through the app already. Did you receive it?

**Comment by bwitt** [comment] 2021-12-19 20:56
I'm having a similar issue with Transdroid 2.5.21 (241) with a qbittorrent server; I think transdroid is not re-authenticating when it needs to.  Here are the logs I've seen on the server:

```
... 
<many requests within ~30s of each other, all 200s>
...
x.x.x.x - - [19/Dec/2021:17:18:53 +0000] "POST /api/v2/torrents/info HTTP/1.1" 200 201095 "-" "Transdroid Torrent Connect"
x.x.x.x - - [19/Dec/2021:17:18:53 +0000] "POST /api/v2/sync/maindata?rid=0 HTTP/1.1" 200 240869 "-" "Transdroid Torrent Connect"
x.x.x.x - - [19/Dec/2021:20:39:03 +0000] "POST /api/v2/torrents/info HTTP/1.1" 403 9 "-" "Transdroid Torrent Connect"
x.x.x.x - - [19/Dec/2021:20:39:03 +0000] "POST /api/v2/sync/maindata?rid=0 HTTP/1.1" 403 9 "-" "Transdroid Torrent Connect"
x.x.x.x - - [19/Dec/2021:20:39:32 +0000] "POST /api/v2/torrents/add HTTP/1.1" 403 9 "-" "Transdroid Torrent Connect"
```

after the gap from `17:18:53` to `20:39:32` server returns 403s and the client never re-authenticated.  At this point my transdroid is spinning and I have to close it and re-open.

here's the logs from the transdroid side
```
37255 -- Sun Dec 19 12:39:04 PST 2021 -- 3 -- Error: AuthenticationFailure exception: Response code 403
37256 -- Sun Dec 19 12:39:04 PST 2021 -- 3 -- Error: AuthenticationFailure exception: Response code 403
37257 -- Sun Dec 19 12:39:04 PST 2021 -- 3 -- AuthenticationFailure exception: Response code 403
37258 -- Sun Dec 19 12:39:04 PST 2021 -- 3 -- AuthenticationFailure exception: Response code 403
37259 -- Sun Dec 19 12:39:33 PST 2021 -- 3 -- Error: AuthenticationFailure exception: Response code 403
37260 -- Sun Dec 19 12:39:33 PST 2021 -- 3 -- AuthenticationFailure exception: Response code 403 
```

I think it used to keep track of when the token would expire and preemptively re-authenticate, and now it's not doing that.

**Comment by kevin-stuart** [comment] 2021-12-21 15:03
I was delighted at this fix https://github.com/erickok/transdroid/pull/599 - but it introduced this problem even with older versions with qBittorrent. I think the problem is observed correctly that auth is not renewed. After a long time of not using Transdroid it fails and if you close it via swipe it will work again.

**Comment by erickok** [comment] 2021-12-21 16:31
Hmm yeah since a single connection is now used (but never renewed) it doesn't reauthenticate. Will need to fix this.

**Comment by SegiH** [comment] 2021-12-22 18:36
Is that because of the change you made by adding synchronized to some of the function definitions ? 

I'll be happy to submit a PR if you can point me in the general direction of where to look to locate the issue. I am looking through the commit history to see if I can find the issue.

**Comment by SegiH** [comment] 2021-12-22 18:46
Actually, I think that I may have found the problem. All of the adapters had a similar change where you added synchronized. Since this 

`https://github.com/erickok/transdroid/blob/3869be4befef39ffc75965386e256c6873f3f67e/app/src/main/java/org/transdroid/daemon/adapters/deluge/DelugeAdapter.java#L577`

I am wondering if the logic in 
https://github.com/erickok/transdroid/blob/3869be4befef39ffc75965386e256c6873f3f67e/app/src/main/java/org/transdroid/daemon/adapters/deluge/DelugeAdapter.java#L478 to #L518 needs to be moved to Initialize to reauthenticate

**Comment by bwitt** [comment] 2021-12-22 20:38
maybe the checks for a non-null session cookie e.g. 

https://github.com/erickok/transdroid/blob/3869be4befef39ffc75965386e256c6873f3f67e/app/src/main/java/org/transdroid/daemon/adapters/deluge/DelugeAdapter.java#L479
https://github.com/erickok/transdroid/blob/3869be4befef39ffc75965386e256c6873f3f67e/app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java#L192

need to also check for age > something

**Comment by SegiH** [comment] 2021-12-22 20:50
I recompiled the app with a different package name for testing purposes and changed 

`if (sessionCookie == null) { `

to

`if (httpclient == null || sessionCookie == null) {`

Do you think that that should cover it ?

**Comment by SegiH** [comment] 2021-12-22 21:09
I just got this error again. My solution doesn't work

**Comment by SegiH** [comment] 2021-12-25 07:38
Update to my last post. This is not fixed. This attempt to fix did not work

**Comment by bwitt** [comment] 2021-12-25 19:44
I think https://github.com/erickok/transdroid/pull/603 should fix; tested locally with qbittorrent but I don't have a deluge 1.2 to test with.

**Closed** 2021-12-28 21:02 UTC
