### ISSUE TITLE
Miui 10 bug

### ISSUE THREAD

**Issue by Zaguzin** [erickok/transdroid#484] opened 2019-01-20 16:02 UTC
java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ListAdapter android.widget.ListView.getAdapter()' on a null object reference
	at org.transdroid.core.gui.TorrentsFragment.updateViewVisibility(TorrentsFragment.java:469)
	at org.transdroid.core.gui.TorrentsFragment.updateIsLoading(TorrentsFragment.java:447)
	at org.transdroid.core.gui.TorrentsActivity.onTorrentsRetrieved(TorrentsActivity.java:1311)
	at org.transdroid.core.gui.TorrentsActivity_.access$201(TorrentsActivity_.java:44)
	at org.transdroid.core.gui.TorrentsActivity_$5.run(TorrentsActivity_.java:283)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:155)
	at android.app.ActivityThread.main(Unknown Source:65)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:342)

Xiaomi redmi note 5, miui 10 all firemware, android 8.1.

**Comment by Zaguzin** [comment] 2019-01-20 16:03
Please describe your problem:



Transdrone 2.5.14 (234)
uTorrent settings: http://zaguzin@192.168.1.45:8088

Connection and error log:
1193 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ListAdapter android.widget.ListView.getAdapter()' on a null object reference
1194 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsFragment.updateViewVisibility(TorrentsFragment.java:469)
1195 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsFragment.updateIsLoading(TorrentsFragment.java:447)
1196 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity.onTorrentsRetrieved(TorrentsActivity.java:1311)
1197 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity_.access$201(TorrentsActivity_.java:44)
1198 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity_$5.run(TorrentsActivity_.java:283)
1199 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: android.os.Handler.handleCallback(Unknown Source:2)
1200 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: android.os.Handler.dispatchMessage(Unknown Source:4)
1201 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: android.os.Looper.loop(Unknown Source:155)
1202 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: android.app.ActivityThread.main(Unknown Source:65)
1203 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: java.lang.reflect.Method.invoke(Native Method)
1204 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
1205 -- Sun Jan 20 22:54:44 GMT+07:00 2019 -- 6 -- E: com.android.internal.os.ZygoteInit.main(Unknown Source:342)

**Comment by erickok** [comment] 2019-01-21 07:55
Thanks for the report. I have seen this crash in reports, but am not able to reproduce it, so it might be bound to some ROM indeed. Cab you reproduce it, and if so how?

**Comment by Zaguzin** [comment] 2019-01-21 09:20
I just open the program. When you close or minimize the button "back" this error occurs. Only then.

**Comment by Zaguzin** [comment] 2019-01-21 09:46
Video:
https://youtu.be/2-Uz55ARw9E
Rom:
https://cdn1.savepice.ru/uploads/2019/1/21/edc7f09792bffd2d39d356cf490d266f-full.png

**Comment by paour** [comment] 2019-03-24 06:09
I don't think this is specific to a given phone. It's because when your @Background methods call a @UiThread method they don't check that the activity hasn't been destroyed first.

My recommendation would be to wrap the body of all @Background methods in a try/catch to handle this. Your code is amazingly free of random tries, but a proper fix for this (keeping track of whether the activity has been destroyed, or interrupting background tasks when it happens) requires a rewrite with kotlin coroutines our RxJava and is probably daunting.

**Closed** 2019-04-24 22:07 UTC
Labels: bug
