### ISSUE TITLE
Connecting to rTorrent 0.9.4

### ISSUE THREAD

**Issue by tuplink** [erickok/transdroid#207] opened 2015-05-18 00:19 UTC
i upgraded to 0.9.4 and now cant connect with transdroid

enabled xmlrpc logging in rtorrent and get this

27:CONTENT_LENGTH1869SCGI1,<?xml version="1.0" encoding="UTF-8"?>

<methodCall>
<methodName>d.multicall</methodName>

<params>
<param>
<value>
<string>main</string>
</value>
</param>

<param>
<value>
<string>d.get_hash=</string>
</value>
</param>

<param>
<value>
<string>d.get_name=</string>
</value>
</param>

<param>
<value>
<string>d.get_state=</string>
</value>
</param>

<param>
<value>
<string>d.get_down_rate=</string>
</value>
</param>

<param>
<value>
<string>d.get_up_rate=</string>
</value>
</param>

<param>
<value>
<string>d.get_peers_connected=</string>
</value>
</param>

<param>
<value>
<string>d.get_peers_not_connected=</string>
</value>
</param>

<param>
<value>
<string>d.get_peers_accounted=</string>
</value>
</param>

<param>
<value>
<string>d.get_bytes_done=</string>
</value>
</param>

<param>
<value>
<string>d.get_up_total=</string>
</value>
</param>

<param>
<value>
<string>d.get_size_bytes=</string>
</value>
</param>

<param>
<value>
<string>d.get_creation_date=</string>
</value>
</param>

<param>
<value>
<string>d.get_left_bytes=</string>
</value>
</param>

<param>
<value>
<string>d.get_complete=</string>
</value>
</param>

<param>
<value>
<string>d.is_active=</string>
</value>
</param>

<param>
<value>
<string>d.is_hash_checking=</string>
</value>
</param>

<param>
<value>
<string>d.get_base_path=</string>
</value>
</param>

<param>
<value>
<string>d.get_base_filename=</string>
</value>
</param>

<param>
<value>
<string>d.get_message=</string>
</value>
</param>

<param>
<value>
<string>d.get_custom=addtime</string>
</value>
</param>

<param>
<value>
<string>d.get_custom=seedingtime</string>
</value>
</param>

<param>
<value>
<string>d.get_custom1=</string>
</value>
</param>

<param>
<value>
<string>d.get_peers_complete=</string>
</value>
</param>

<param>
<value>
<string>d.get_peers_accounted=</string>
</value>
</param>
</params>
</methodCall>

---
Status: 200 OK
Content-Type: text/xml
Content-Length: 312

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-506</i4></value></member>
<member><name>faultString</name>
<value><string>Method 'd.multicall' not defined</string></value></member>
</struct></value>
</fault>
</methodResponse>

---

i think the key here is "Method 'd.multicall' not defined"

**Comment by tuplink** [comment] 2015-05-18 00:29
looks as if this is a dupe of 193, any chance of getting this merged?

**Comment by erickok** [comment] 2015-06-01 10:54
Correct, duplicate of #193.

**Closed by erickok** 2015-06-01 10:54 UTC
