### ISSUE TITLE
Communication error with deluge

### ISSUE THREAD

**Issue by X-static** [erickok/transdroid#370] opened 2017-05-03 17:27 UTC
Hi, I have transdroid connected to deluge and sometimes, randomly, without an apparent pattern, I'm getting the following error: "Error during communication; check you connection".

Deluge version is 1.3.14 running on windows 7.
Transdroid version is latest 2.5.8.

**Comment by maersk** [comment] 2017-05-06 11:00
Hi I have the same issue with deluge, can confirm the problem.

**Comment by maersk** [comment] 2017-05-06 11:09
I am using deluge 1.3.10 on a rapsberry pi 3 with latest transdroid version

**Comment by danbiba** [comment] 2017-05-26 01:40
I'm having the same issue pretty frequently on a pi b+ with the latest deluge. Works sometimes and sometimes had connection error. Is there any fix for this?

**Comment by Freethefire** [comment] 2017-06-11 16:08
Same here but on Windows 10, I'm running daemon as service.

**Comment by ikus060** [comment] 2017-07-03 01:29
Hello,

I'm having the same issue. It's seams to be realted to a bad formated request made by Transdroid.

See the log in Deluge-web:
```
[ERROR   ] 21:21:59 json_api:275 Invalid JSON request content-type: text/plain; charset=ISO-8859-1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 297, in render
    d = self._on_json_request(request)
  File "/usr/lib/python2.7/dist-packages/deluge/ui/web/json_api.py", line 257, in _on_json_request
    raise JSONException(message)
JSONException: Invalid JSON request content-type: text/plain; charset=ISO-8859-1
```
With some tweak here is payload.
```
{"method":"auth.login","params":["CHANGEME"],"id":1}
```
From what I understand, Transdroid need to change the content-type pass for the auth.login.

**Comment by ikus060** [comment] 2017-07-03 01:39
Seams related to the following line.
https://github.com/erickok/transdroid/blob/bc4f442d8bcd89f20e16c081efc52b40a28070e7/app/src/main/java/org/transdroid/daemon/Deluge/DelugeAdapter.java#L527
I suspect a bug in Apache HttpClient regarding the encoding. 
```
httppost.setEntity(new StringEntity(json.toString(), HTTP.UTF_8));
```
should fix the problem and work arround the apache client bug.

**Comment by chadblose** [comment] 2017-08-28 20:22
I am also experiencing this same issue. Running deluged on Linux.

**Comment by erickok** [comment] 2017-11-14 19:36
While @ikus060 's analysis sounds solid and I have just pushed a patch, I was not able to reproduce (and thus test the fix for) the issue. So 🤞.

**Comment by erickok** [comment] 2018-10-05 21:04
Closing as this is fixed to the best of my knowledge.

**Closed by erickok** 2018-10-05 21:04 UTC
