### ISSUE TITLE
Unable to add .torrent from android file browser

### ISSUE THREAD

**Issue by shizeon** [erickok/transdroid#382] opened 2017-07-07 20:03 UTC
I am unable to select a .torrent file in transdrone with the android file chooser when initiating from within transdrone. I see the file, but it is grayed out like it isn't a supported file. I'm running transdrone with Deluge 1.3.12 and everything else works fine. I'm able to add magnet links, and also manage every other aspect ok. 

If I open the 'Downloads' app first and select the .torrent file transdrone opens the file correctly and adds it to the queue. It is just when clicking the + -> File option it is grayed out.

Screenshot:
![screenshot_20170707-125724](https://user-images.githubusercontent.com/682257/27974810-658482ba-6314-11e7-833b-944876b9172f.png)

**Comment by dawidd6** [comment] 2017-07-09 15:16
I can confirm this. Android 7.1.2

**Comment by dpsenner** [comment] 2017-07-10 07:42
Confirmed also on Android 6.0.1

**Comment by dawidd6** [comment] 2017-07-10 08:35
https://github.com/erickok/transdroid/blob/master/app/src/main/java/org/transdroid/core/gui/search/FilePickerHelper.java#L45

Maybe it should be `setType("application/x-bittorrent")` ?

**Comment by erickok** [comment] 2017-07-10 09:07
This is a known issue due to changes in newer Android versions. Transdroid doens't have (or request) the permissions to read those files. As a workaround you can use a file manager such as Dir and/or directly 'open' torrents via the download manager.

**Comment by dpsenner** [comment] 2017-07-16 09:31
Unfortunately, opening torrents from the download manager does not work. It works only by using a file manager. I would not mind granting transdroid those permissions if it would ask me to do so. *grinning* :+1:

(Shameless plug) Note that I'm not going to need this feature anytime soon since I was able to set up torrents to be loaded and started from an rss feed in an automated way. See https://github.com/dpsenner/bridge-from-torrent-rss-feed-to-rtorrent for more information.

It would anyway be nice if one would not have to use an external file manager to add torrent files.

**Comment by alonalbert** [comment] 2018-01-03 06:48
Update:
It turns out that the reason the file is grayed out is not a permission issue but rather, a MIME Type issue.

I sent Eric a potential fix which he is testing to make sure it works on a wider range if device than I have access to. Hopefully, it will pass.

**Comment by erickok** [comment] 2018-01-11 15:59
Fixed via #405

**Closed by erickok** 2018-01-11 15:59 UTC
Labels: bug
