### ISSUE TITLE
No way to set proxy?

### ISSUE THREAD

**Issue by burnup** [erickok/transdroid#217] opened 2015-06-24 06:08 UTC
After browsing through all the settings I couldn't find a way to set a proxy for all Transdroid data traffic. My torrent box is a Tor hidden service so I'd love to have Transdroid be able to resolve the .onion address.

**Comment by burnup** [comment] 2015-06-24 06:09
I mean by connecting to a local instance of Orbot, obviously.

**Comment by erickok** [comment] 2015-08-28 10:27
Possible duplicate of #163. Have to investigate some time on the future.

**Closed** 2016-05-20 12:17 UTC
Labels: wontfix
