### ISSUE TITLE
Fatal error when app is in background

### ISSUE THREAD

**Issue by merlin-zaraza** [erickok/transdroid#464] opened 2018-10-17 16:17 UTC
Version: 2.5.10
Phone: Nexus 6p
Android: 8.1

Error:
```
2018-10-17 11:14:41.297 19465-19465/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.transdroid.lite, PID: 19465
    java.lang.RuntimeException: Unable to start receiver org.transdroid.core.service.AlarmReceiver_: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.transdroid.lite/org.transdroid.core.service.ServerCheckerService_ }: app is in background uid UidRecord{ee2c5c u0a77 RCVR idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.transdroid.lite/org.transdroid.core.service.ServerCheckerService_ }: app is in background uid UidRecord{ee2c5c u0a77 RCVR idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at org.transdroid.core.service.AlarmReceiver.onReceive(AlarmReceiver.java:36)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
        at android.app.ActivityThread.-wrap17(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by sinicide** [comment] 2018-10-22 13:23
I've also been noticing this error lately as well.
Version: 2.5.12
Phone: Pixel
Android: 8.1

    10-22 08:08:56.037 E/AndroidRuntime( 2864): FATAL EXCEPTION: main
    10-22 08:08:56.037 E/AndroidRuntime( 2864): Process: org.transdroid.full, PID: 2864
    10-22 08:08:56.037 E/AndroidRuntime( 2864): java.lang.RuntimeException: Unable to start receiver org.transdroid.core.service.AlarmReceiver_: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.transdroid.full/org.transdroid.core.service.ServerCheckerService_ }: app is in background uid UidRecord{b43e68a u0a164 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3211)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.app.ActivityThread.access$2200(ActivityThread.java:178)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.os.Handler.dispatchMessage(Handler.java:106)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.os.Looper.loop(Looper.java:164)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.app.ActivityThread.main(ActivityThread.java:6524)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at java.lang.reflect.Method.invoke(Native Method)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:460)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.transdroid.full/org.transdroid.core.service.ServerCheckerService_ }: app is in background uid UidRecord{b43e68a u0a164 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1531)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.app.ContextImpl.startService(ContextImpl.java:1486)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at org.transdroid.core.service.AlarmReceiver.onReceive(AlarmReceiver.java:36)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3202)
    10-22 08:08:56.037 E/AndroidRuntime( 2864): 	... 8 more

**Comment by erickok** [comment] 2018-10-22 17:10
I'm working on it, but it's far from a one-liner... Disable all your
background services for now as a workaround.

**Comment by erickok** [comment] 2018-10-23 18:04
Duplicate of #462. (I am workig on it.)

**Closed by erickok** 2018-10-23 18:04 UTC
