### ISSUE TITLE
History results still with white font

### ISSUE THREAD

**Issue by fernandog** [erickok/transdroid#247] opened 2015-10-16 12:29 UTC
@erickok 
![2015-10-16 09 23 48](https://cloud.githubusercontent.com/assets/2620870/10541557/6653cd76-73e8-11e5-90ca-d6100cd01a88.png)

**Comment by erickok** [comment] 2015-11-04 15:49
Hmm this should have been fixed in the latest release. Are you using Transdroid 2.5.4? What OS version are you running?

**Comment by fernandog** [comment] 2015-11-04 15:56
Yes. 2.5.4
Android 4.2.2 - with Samsung Touchwiz

**Comment by fernandog** [comment] 2015-11-23 21:27
@erickok still happening with 2.5.5. confirm?

**Comment by erickok** [comment] 2015-11-24 10:41
Yes, I confirm. I tried to fix this yesterday but failed to do so. It only happens on Android 4 and for some bizarre reason only in the Search screen, while the main screen works as intended. Don't know yet why; hope to fix this for the next release.

**Comment by fernandog** [comment] 2015-11-24 10:56
No problem. Compability... i know

**Closed** 2020-06-19 17:57 UTC
Labels: bug
