### ISSUE TITLE
Port number optional

### ISSUE THREAD

**Issue by Tiwing1** [erickok/transdroid#491] opened 2019-03-27 03:09 UTC
Reverse proxy takes care of port number, would like to just put url and not have 8112 forced at end of url. Cheers

**Comment by erickok** [comment] 2019-03-27 08:22
It's the very first option under Advanced Settings. (Note there is no header.) Duplicate of #314.

**Comment by supermamie** [comment] 2019-04-16 08:42
I had the exact same problem and I needed this comment to find that there was a port option.
It is really not visible and looked like a title.
Thanks @erickok :smiley:

**Closed** 2019-04-24 20:47 UTC
