### ISSUE TITLE
FC with rTorrent server

### ISSUE THREAD

**Issue by Albvadi** [erickok/transdroid#403] opened 2017-12-28 11:17 UTC
Hi,
first of all, thanks for this great app!

I´m using it in two devices: Sony Xperia Z2 Tablet and Xiaomi Mi5s phone, both with 3 servers configured (one rTorrent, one Deluge for testing and one Transmission for testing).

In tablet, all servers are working perfect. I have a settings.json exported.
In phone, I imported the settings and only Deluge and Transmission works. If I select rTorrent server, app crash. If my default server it´s rTorrent, app crash constantly and I need to delete data an reconfigure again. It´s configured with SCGI point mount (/rutorrent/plugins/httprpc/action.php)

Versions and logs:

- Android: 6.0.1
- MIUI: Global 8.5 Stable (8.5.4.0 - MAGMIED)
- rTorrent: 0.9.6
- rutorrent: 3.7
- Transdroid: 2.5.9 (tested all from 2.5.6)

Log: 
```log
Transdroid 2.5.9 (229)
Transmission settings: http://username@<server>:9091

Connection and error log:
203 -- Thu Dec 28 11:29:34 GMT+01:00 2017 -- 3 -- Boot signal received, starting app update checker service
204 -- Thu Dec 28 11:29:34 GMT+01:00 2017 -- 3 -- Execute session-get request to http://<server>:9091/transmission/rpc
205 -- Thu Dec 28 11:29:35 GMT+01:00 2017 -- 3 -- Receive HTTP 409 with new session code; now try again for the actual request
206 -- Thu Dec 28 11:29:35 GMT+01:00 2017 -- 3 -- Retry to execute session-get request, now with X-Transmission-Session-Id: hHeNu3j0S7HD4MBuYsl8Z4kfQV8L2jRnllt9eKHGrNFDM22E
207 -- Thu Dec 28 11:29:35 GMT+01:00 2017 -- 3 -- Received content response starting with {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-ti...
208 -- Thu Dec 28 11:29:35 GMT+01:00 2017 -- 3 -- Execute session-get request to http://<server>:9091/transmission/rpc
209 -- Thu Dec 28 11:29:35 GMT+01:00 2017 -- 3 -- Received content response starting with {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-ti...
210 -- Thu Dec 28 11:29:35 GMT+01:00 2017 -- 3 -- Execute torrent-get request to http://<server>:9091/transmission/rpc
211 -- Thu Dec 28 11:29:35 GMT+01:00 2017 -- 3 -- Received content response starting with {"arguments":{"torrents":[{"addedDate":1514391701,"comment":"","desiredAvailable":0,"doneDate":15143...
212 -- Thu Dec 28 11:29:35 GMT+01:00 2017 -- 3 -- Execute session-get request to http://<server>:9091/transmission/rpc
213 -- Thu Dec 28 11:29:36 GMT+01:00 2017 -- 3 -- Received content response starting with {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-ti...
214 -- Thu Dec 28 11:30:45 GMT+01:00 2017 -- 3 -- Cannot retrieve latest app or search module version code from the site: java.lang.NumberFormatException: Invalid int: "404: Not Found"

//Until here (I think...), load mi default server, wich it´s Transmission.

// Now, I select rTorrent

215 -- Thu Dec 28 11:31:04 GMT+01:00 2017 -- 3 -- Calling system.client_version with params [ ]
216 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 3 -- Calling system.client_version with params [ ]
217 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
218 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
219 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
220 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
221 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.auth.DigestScheme.isGbaScheme(DigestScheme.java:210)
222 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.auth.DigestScheme.isGbaScheme(DigestScheme.java:210)
223 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.auth.DigestScheme.processChallenge(DigestScheme.java:176)
224 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.auth.DigestScheme.processChallenge(DigestScheme.java:176)
225 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.DefaultRequestDirector.processChallenges(DefaultRequestDirector.java:1112)
226 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.DefaultRequestDirector.processChallenges(DefaultRequestDirector.java:1112)
227 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:995)
228 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:995)
229 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:491)
230 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:491)
231 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
232 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
233 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
234 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
235 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
236 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:381)
237 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
238 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:381)
239 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:197)
240 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:197)
241 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.daemon.Rtorrent.RtorrentAdapter.makeRtorrentCall(RtorrentAdapter.java:341)
242 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.daemon.Rtorrent.RtorrentAdapter.makeRtorrentCall(RtorrentAdapter.java:341)
243 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.daemon.Rtorrent.RtorrentAdapter.executeTask(RtorrentAdapter.java:113)
244 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.daemon.task.DaemonTask.execute(DaemonTask.java:79)
245 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.daemon.Rtorrent.RtorrentAdapter.executeTask(RtorrentAdapter.java:113)
246 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity.refreshTorrents(TorrentsActivity.java:959)
247 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.daemon.task.DaemonTask.execute(DaemonTask.java:79)
248 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity_.access$1401(TorrentsActivity_.java:55)
249 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity.refreshTorrents(TorrentsActivity.java:959)
250 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity_.access$1401(TorrentsActivity_.java:55)
251 -- Thu Dec 28 11:31:05 GMT+01:00 2017 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity_$18.execute(TorrentsActivity_.java:524)
252 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity_$18.execute(TorrentsActivity_.java:524)
253 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:401)
254 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:401)
255 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
256 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.FutureTask.run(FutureTask.java:237)
257 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
258 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
259 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.FutureTask.run(FutureTask.java:237)
260 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
261 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
262 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
263 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
264 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
265 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
266 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
267 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.lang.Thread.run(Thread.java:818)
268 -- Thu Dec 28 11:31:06 GMT+01:00 2017 -- 6 -- E: java.lang.Thread.run(Thread.java:818)

// App crashed. Running again...

269 -- Thu Dec 28 11:31:07 GMT+01:00 2017 -- 3 -- Boot signal received, starting app update checker service
270 -- Thu Dec 28 11:31:07 GMT+01:00 2017 -- 3 -- Execute session-get request to http://<server>:9091/transmission/rpc
271 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Receive HTTP 409 with new session code; now try again for the actual request
272 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Retry to execute session-get request, now with X-Transmission-Session-Id: hHeNu3j0S7HD4MBuYsl8Z4kfQV8L2jRnllt9eKHGrNFDM22E
273 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Received content response starting with {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-ti...
274 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Execute session-get request to http://<server>:9091/transmission/rpc
275 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Received content response starting with {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-ti...
276 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Execute session-get request to http://<server>:9091/transmission/rpc
277 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Received content response starting with {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-ti...
278 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Execute torrent-get request to http://<server>:9091/transmission/rpc
279 -- Thu Dec 28 11:31:08 GMT+01:00 2017 -- 3 -- Received content response starting with {"arguments":{"torrents":[{"addedDate":1514391701,"comment":"","desiredAvailable":0,"doneDate":15143...
```

Thanks!!

**Comment by kalyway** [comment] 2017-12-28 20:06
I'm also have the same issue with rtorrent.

**Comment by erickok** [comment] 2018-01-02 14:42
Duplicate of #315 there isn't much I can do (except not crash, but that's not going to help you much) except for upgrading the whole network layer to not use Apache HTTP Client (see #402).

**Closed by erickok** 2018-01-02 14:42 UTC
