### ISSUE TITLE
Custom ports

### ISSUE THREAD

**Issue by J316** [erickok/transdroid#237] opened 2015-08-30 11:19 UTC
When selecting the torrent software to use it automatically chooses the port based on that choice. You should definitely allow to choose custom ports

**Comment by erickok** [comment] 2015-08-30 11:41
Duplicate of #236. Hard to find?

**Closed by erickok** 2015-08-30 11:41 UTC

**Comment by J316** [comment] 2015-08-30 11:51
Not hard but confusing, since it's in the same sector of the local network. It should be moved to the main page since it's not an advanced setting but a very basic one.

**Comment by sperfect** [comment] 2016-09-09 12:19
Thanks. It's because the previous form has a Title bar, so the eye isn't expecting something there...
