### ISSUE TITLE
QBittorrent V5.0

### ISSUE THREAD

**Issue by papampi** [erickok/transdroid#673] opened 2024-10-09 18:42 UTC
Hi,
QBittorrent updated to V5.0.0 and the api has changed Pause/Resume to Stop/Start.
Transdroid can't pause/resume QBittorrent v5.0 anymore.

**Comment by bwitt** [comment] 2024-10-10 04:51
dupe of https://github.com/erickok/transdroid/issues/672

**Closed** 2024-10-10 06:51 UTC
