### ISSUE TITLE
Fully black amoled theme.

### ISSUE THREAD

**Issue by blackCauldron7** [erickok/transdroid#586] opened 2021-04-22 19:52 UTC
Just for the aesthetics it would be cool to have the top and bottom and navigation bars to be black too.

And is the f-droid version discontinued it hasn't been updated to the latest version.

Thanks for the cool app :)

**Comment by erickok** [comment] 2021-05-23 08:43
Seems like a duplicate of #521 

I am not myself taking care of the F-Droid builds. Is there anything that I should do?

**Closed by erickok** 2021-05-23 08:43 UTC
