### ISSUE TITLE
Tixati support. 

### ISSUE THREAD

**Issue by ognjen73** [erickok/transdroid#552] opened 2020-06-13 17:34 UTC
Dear Eric, 
Please add support for Tixati torrent client.
In my opinion it is one of the best.
It has web ui so it should work with Transdroid.
Making support would make my and other people's life much easier. 
Thank you.
Ognjen

**Comment by lozbrown** [comment] 2020-06-15 07:15
Duplicate of
#135 

Weirdly the web ui has no underlying API making external clients very difficult. Unless thats changed significantly in the years since

**Comment by ognjen73** [comment] 2020-06-15 07:59
I am not the developer so I do not know what kind of Web API is needed for Tixati to communicate with Transdroid.
The issue #135 was submitted six years ago. Maybe the things have changed. 
Could some developer check the current state of Tixati API and implement support if it is not hard?
Thank you very much.

**Comment by erickok** [comment] 2020-06-15 10:46
I've looked again through the site and searched their [support forum](https://forum.tixati.com/support), but cannot find anything about an API. So sorry, but I have to close until it has some official way to access their data. Manually parsing html is just too error prone and maintenance-intensive.

**Closed by erickok** 2020-06-15 10:46 UTC
