### ISSUE TITLE
cannot connect to deluge from transdrone

### ISSUE THREAD

**Issue by davidtuti** [erickok/transdroid#297] opened 2016-04-09 16:24 UTC
Hi,
I setup deluge torrent client in my raspberry.
Now I'm trying to set up transdrone to control torrents from my phone. But allways fail:
"Web interface not connected to a execution service"
I can access from phone via url.
Could you help me please?
Thanks and sorry for my English!

**Comment by TheSoftwareDev** [comment] 2016-04-09 16:27
Is the deluge web interface attached to the deluge service? I normally
receive this error after a server restart, and logging into the web
interface will prompt with a "Connect" window following the password prompt.

Connecting via Web, and then restarting Transdrone should correct this.

**Comment by erickok** [comment] 2016-04-14 15:15
Duplicate of #298.

**Closed by erickok** 2016-04-14 15:15 UTC
