### ISSUE TITLE
Connect to Deluge using reverse proxy not working

### ISSUE THREAD

**Issue by gurabli** [erickok/transdroid#302] opened 2016-05-18 09:18 UTC
Hi,
I'm running Deluge behind a reverse proxy, SSL enabled, and it has authentication when I access my home server, the Deluge too. 
I can access Deluge from phone's Chrome without any problem: https://server.address.com/deluge
The I enter my username and password, I am then at the Deluge login, where I need to enter password for Deluge.

I see it was asked already and actually solved, but no description was given how to configure Transdroid with the above configuration. Could you please help me?

**Comment by erickok** [comment] 2016-05-20 07:34
Duplicate of #265. You can enter a folder (the /deluge part for you) in the Advanced Settings. Don't forget to set the port (443 for you) either.

**Closed by erickok** 2016-05-20 07:34 UTC

**Comment by gurabli** [comment] 2016-05-20 08:17
Sorry for the duplicate. I tried /folder and port 443 settings, and it didn't work. Then I realized the problem was that the Deluge webui was not connected to the daemon automatically. I fixed this and everything is working excellent now. Thank you for the great app erickok!

For those who are running Deluge behind reverse proxy, with SSL, here is how to configure Transdroid:

1. Make sure that Deluge webui automatically connects to the Deluge daemon. Stop deluged and deluge-web services. Edit web.conf in you Deluge config directory, and add the default daemon (obviously change the below ip and port if yours is different):

"default_daemon": "127.0.0.0:58846",

2. In Transdroid set your host name, your user name and password if you use authentication to access your reverse proxy (should use one). If not, leave it blank.

3. Set you Deluge web password

4. Enter Advanced settings:
- set port number to 443 (if you are using ssl https, strongly recommended)
- set Folder, in my case it is: /deluge
- thick Use SSL (obviously if you are using SSL)
- optionally thick Accept all SSL certificates

5. Set your Local IP or host, port in case if you want to access Deluge from your home network.

Hope it helps!

**Comment by erickok** [comment] 2016-05-20 08:26
No worries and thanks for the additional details.

If you are willing to help, would you be interested in writing the setup tutorial for Deluge for my website, like I did for µTorrent at http://www.transdroid.org/download/%C2%B5torrent/ ?
