### ISSUE TITLE
qBittorrent v3.3.13 - "Internal error building request"

### ISSUE THREAD

**Issue by GUiHKX** [erickok/transdroid#386] opened 2017-08-01 20:11 UTC
I'm using qBittorrent v3.3.13 on Linux, and I can remote control just fine if I use qBittorrent Controller for Android, but I get this "Internal error building request" message when I use Transdrone.

**Comment by erickok** [comment] 2017-08-02 06:46
Duplicate of #380

**Closed by erickok** 2017-08-02 06:46 UTC
