### ISSUE TITLE
Remember download paths

### ISSUE THREAD

**Issue by Steve2Go** [erickok/transdroid#301] opened 2016-05-07 00:37 UTC
Hi there.

It's great to see we can now set the download location - would it be possible to remember the last 5 or 10 download locations?
Other clients have this and it's a great time saver, especially on the small screen.. And with case sensitive file systems.

**Comment by erickok** [comment] 2016-05-20 07:35
Duplicate of #48.

**Closed by erickok** 2016-05-20 07:35 UTC
