### ISSUE TITLE
rss not working

### ISSUE THREAD

**Issue by svyaznoy362** [erickok/transdroid#657] opened 2023-06-20 10:45 UTC
Good afternoon.  rss stopped working normally, data can be uploaded from the 10th time, please fix it

**Comment by svyaznoy362** [comment] 2023-06-20 10:46
![Uploading Screenshot_2023-06-20-13-41-58-926_org.transdroid.full.jpg…]()

**Comment by erickok** [comment] 2023-06-20 11:58
I'm sorry, but I don't understand your issue. Is some RSS feed not parsing/showing correctly? It will be hard to tell what the problem is without the url of the rss feed.

**Comment by svyaznoy362** [comment] 2023-06-20 15:37
> 

https://www.dropbox.com/s/uz4hcnv7hoq4tc0/Screenshot_2023-06-20-13-41-58-926_org.transdroid.full.jpg?dl=0

**Comment by svyaznoy362** [comment] 2023-06-20 15:38
https://teamhd.org/rss.php?c29=1&c25=1&q21=1&q22=1&q34=1&q33=1&q27=1&q28=1&q29=1&q30=1&passkey=4d223cc8465fc05b02e28c6bdeaaaa14

**Comment by erickok** [comment] 2023-06-21 09:11
Your screenshot shows that some feeds cannot be loaded, but without the url I can't investigate why that is. I suspect (if they worked before) that something changes such as that they no longer report links in the same way. But that's guesswork.

**Comment by svyaznoy362** [comment] 2023-06-21 14:35
https://1drv.ms/i/s!ArXofWJ6_4Uogs9txor3oZGBnn8LCw

**Comment by erickok** [comment] 2023-06-22 07:39
I understand you can't send the rss feed (url) here. If you want you may send it private to transdroid@2312.nl and I'll debug it. My guess though is that there are characters that Transdroid can't parse or some malformed XML. Transdroid is quite picky in the structure... more so than most torrent clients.

**Comment by erickok** [comment] 2024-01-24 19:20
This was due to a malformed RSS. Hopefully it is resolved by now. If not, let me know.

**Closed by erickok** 2024-01-24 19:20 UTC
